### ISSUE TITLE
Redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by freddyb** [mozilla/standup#222]
This bug is about all http requests being forwarded to https://standu.ps.
It should not take the path from the request, as this would help identifying incorrect links :-)

**Comment by pmac** [comment]
We've done this via the [SecurityMiddleware](https://docs.djangoproject.com/en/1.8/ref/middleware/#ssl-redirect) built into Django. It does redirect using the requested path, but I don't see how that could leak any sensitive info. Valid urls could more easily be queried by looking for 200s instead of 404s.

This is now live in prod. Thanks!
