### ISSUE TITLE
memory usage too high

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#262]
I have no idea what the memory usage characteristics of the old Standup was. In retrospect, we probably should have sampled a week so we had some data to compare against.

The new Standup is exceeding the Heroku memory usage allotment. It starts out fine, but over time it increases in memory usage until it exceeds the threshold and starts kicking off Heroku alerts.

Some theories:
1. appropriate memory usage that needs to be restrained
2. memory leak somewhere
3. excessive caching somewhere
4. ?

This issue covers fixing Standup on Heroku so that it's not bleeding memory anymore.

**Comment by willkg** [comment]
@pmac tweaked the gunicorn process args to reduce memory usage:

https://github.com/mozilla/standup/commit/db7669074c0687cec9c01f10444c2952d11e63e5

Looking at the Heroku dashboard, I think that isn't deployed, yet. I'm going to deploy that now and check metrics later today.

**Comment by willkg** [comment]
Huh. It looks like it's out there already, but the tags and commit shas on the Heroku activity board for deploys are different. That's ... confusing.

**Comment by willkg** [comment]
This article suggests we should adjust gunicorn to make two workers:

https://devcenter.heroku.com/articles/optimizing-dyno-usage#python

Maybe we want to use gevent workers?

**Comment by pmac** [comment]
We do currently have the `WEB_CONCURRENCY` variable set to 2. I had it at 4, so that's likely why our memory use was too high initially. And I'm a bit weary of gevent workers. It might be fine, but it could also introduce some strange bugs that will be hard to track, and last I tried New Relic doesn't play well with it.

**Comment by willkg** [comment]
I checked Heroku metrics dashboard again and we're still using too much memory. Seems like the process(es) restart and then monotonically increases in memory until it gets killed off. That dashboard only shows 24 hours tops.

New Relic shows the spikes, too, but I think it's averaging the processes, so it only shows like half of what we're seeing on Heroku dashboard. Or something like that. The two sets of numbers are different, but the line has the same shape.

**Comment by pmac** [comment]
I think we're doing okay actually. The processes do use increasing memory, but I think our gunicorn setting of max_requests is what is causing the process restart since I don't see any more `SystemExit` errors in Sentry. So I think maybe it's working as expected. It's still not perfect, clearly, but it will probably work for a while. I think the real answer would be to fire up another Dyno, but I'm not sure if the people paying for this would like to afford that.

**Comment by pmac** [comment]
Huh. Nevermind. I see the memory overage issue that happened last night. I didn't realize that Heroku would allow the dyno to go over like that.

**Comment by willkg** [comment]
Oh--we fixed this! It was #290. Closing it out.
