### ISSUE TITLE
Add the ability to reply_to status posts via website

### ISSUE THREAD

**Issue by Callek** [mozilla/standup#278]
It would be nice to be able to comment on a status, (your own or others) via the website as well as the bot. 

For now, the web UI shows comment stuff but no way to actually comment, causing confusing UX to me

**Comment by willkg** [comment]
When you say "it would be nice", what's the use cases for that? Are you cheering people on? Are you continuing a conversation? Something else?

**Comment by Callek** [comment]
@willkg there is already a comment-ability I'm told (via bot?) and the web UI shows it -- so it makes sense for the website to expose the ability as well rather than attempt to show it with no actual ability.

I'm +0 on having the actual ability to comment at all, but +100 on having the UX be consistent in its display/use of the ability to comment.

e.g. https://www.standu.ps/status/38730/

**Comment by willkg** [comment]
Ok. So this is for parallel feature sets and not otherwise a real need. That's fine.

To be honest, I'm on the fence about keeping `reply_to`. Conversation trees are hard and we have no notification system, so no one ever knows about replies unless they're checking. So unless there's a compelling need, I'm inclined to nix it entirely.

**Comment by pmac** [comment]
Perhaps the naming is the issue. It seems to be more of a "related to" thing. We could perhaps keep the bot's ability to allow people to tie their status to another, and change the wording on the site to "related statuses"... 

This is a similar UX problem to tags. They don't serve any purpose other than being highlighted. We should probably add links to tags that result in a search for similarly tagged statuses, but I'm not sure we want or need such complexity.

**Comment by willkg** [comment]
I don't think `reply_to` is similar to tags. Tags are a way of categorizing or classifying status posts in a way we can't do otherwise. The fact that they're not clickable is just a factor of it having not been implemented. I would like better tag support. #76 covers views by tag.

I think all the uses of `reply_to` I saw were as a cheering kind of thing. I'd like to look at the data to see how it actually got used. I don't think I want to turn it into a `related_to` kind of feature unless someone has a really compelling use for that.

**Comment by pmac** [comment]
Fair enough. I'd be happy with removing replies as well to be clear. I've never used it. I'd be interested to see how much it's been used and for what as well.

**Comment by a2sheppy** [comment]
Why not remove replies and instead add a thumbs-up button so people can celebrate accomplishments? Have it tally those up. Would even be fun to display the tally on the web by actually rendering that many thumbs-up icons along the bottom edge of the status update. :)

**Comment by willkg** [comment]
We nixed replies, so I'm going to close this out.
