### ISSUE TITLE
Github login now takes me to new profile creation, but I've already got a profile

### ISSUE THREAD

**Issue by edunham** [mozilla/standup#323]
I'm 'edunham' on standups and my email there is probably set to 'edunham@mozilla.com', which is a secondary address on my github account. GitHub login used to work fine for me. But I've been super bad about remembering to login to standups since you changed auth around (well really, this is the first time I've tried logging in since the auth change). When I try to login with github,  I get sent to the new profile creation page and it autofills my email as github@edunham.net, which is the publicly viewable email address on my github profile. Not sure if the email thing is relevant to the actual problem, but it seems worth mentioning...

Could you please do whatever it is that tells standups that the 'edunham' user there is in fact the same person as 'edunham' on GitHub? 

Thanks!

**Comment by willkg** [comment]
Hi!

Two things:

1. this is totally my fault--not your fault
2. we switched from Github auth to Auth0, but now have to switch from one way to do Auth0 to a different way that matches Mozilla's new guidelines for Auth0

I'm in the process of doing that work, but keep hitting issues.

I was hoping to finish up that work and then help everyone fix their accounts so it's less likely that we lose stuff in the middle. Plus I was hoping to write some better tools for merging/fixing accounts rather than doing it on the command line which is what I'm doing now.

Is this blocking your work right now? If so, I can do a stopgap fix. If not, I'd like to push fixing this off until after I finish up the Auth0 fixes.

**Comment by willkg** [comment]
Also, I'm super sorry about this. It totally sucks.

**Comment by edunham** [comment]
Don't worry about it; the temporary malfunction is causing me to learn to use the IRC bot for its proper purpose instead of slowing myself down figuring out which tab the web UI is in. My world is a much better place with the current, mostly-working Standups than it would be without it :)

**Comment by willkg** [comment]
You've got two user accounts on Standup now--one with a mozilla.com email address and the other with a edunham.net email address.

Which provider do you want to use for logging into Standup going forward? Github, passwordless email or Mozilla LDAP? Depending on that answer, I'll fix the email address on the correct account.

From this:

> Could you please do whatever it is that tells standups that the 'edunham' user there is in fact the same person as 'edunham' on GitHub?

I suspect you want to use the Github provider. Is that right?

**Comment by edunham** [comment]
I'll bet the `github @ edunham.net` thing is the one that was erroneously created from GitHub login. I wish to use the GitHub provider. Email should either be my Mozilla address or `standups @ edunham.net` .

**Comment by willkg** [comment]
Can you try logging in with the github provider? Then I can merge the accounts in the right direction.

**Comment by edunham** [comment]
I logged in with GitHub and everything worked just fine :)

**Comment by willkg** [comment]
Awesome! I'm going to close this out now. Thank you!
