### ISSUE TITLE
adjust standup users so they can have multiple email addresses

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#425]
Since switching to the SSO, we've had people accidentally log in with the "wrong" email address which then creates a new user. That person then feels bad, writes up an issue, and then someone with access has to merge the new account with the old one.

That's "fine" if it happens once in a while, but I think it's happening more frequently than we would like.

This issue covers tweaking our auth code so that we can associate multiple email addresses with a Django identity rather than just one.

**Comment by willkg** [comment]
I think the code change here is easy. The hard part comes with "how do you add email addresses to an account". For now, I think we can have that admin-administered. Maybe adjust mergeuser so that it adds the new email address to the list for the `--keep` user instead of stomping on it?

The other way to do this requires us to verify email addresses or something like that and we don't have the infrastructure to do that correctly.

**Comment by willkg** [comment]
Here's the big in mozilla-django-oidc we'll need:

https://mozilla-django-oidc.readthedocs.io/en/stable/installation.html#connecting-oidc-user-identities-to-django-users

We really want email addresses to uniquely match a Django user. We should probably add an `EmailAddress` table which makes email addresses unique. Then have a one (StandupUser) to many (EmailAddress) relationship. Then we match oidc.email to EmailAddress to StandupUser.

We'll need to keep the email address the user signed in with in the Django session and display that across the site.

We'll need to either add stuff to the admin to manage email addresses or we'll need to add command line things to manage email addresses (or both--I still have problems using the admin).

We'll want a process and possibly some tooling to help admin know that a request to add an email address to an account is valid. I don't have good ideas on this. Maybe because Standup is small, we can push this off for a bit and rely on data in phonebook and other sources of truth.

I think I may try to tackle this this week because it's a drag and it's going to get worse as the SSO stuff rolls out.

**Comment by willkg** [comment]
I talked with @johngian and @jezdez and others about this in our secret poker club and it was suggested we bring this up with @gdestuynder because it's likely to be a problem for other SSO-using sites so it's prudent we all think about this together.

**Comment by gdestuynder** [comment]
I'm going to try to be as clear and concise as possible, because I know this stuff gets complex quickly -bear with me!

# On verified emails/accounts/etc being available and useable through IAM/SSO
- Mozilla IAM profiles support additional emails, accounts, etc with a flag that indicate if it's been strongly verified that this email/account/etc belongs to you. See also [CIS profiles](https://github.com/mozilla-iam/cis/blob/master/docs/Profiles.md) and the example [here](https://github.com/mozilla-iam/cis/blob/master/tests/data/profile-good.json#L21-L22) (the flag is `verified`)
- These profiles are not yet sent for all users as we're fixing some related issues (in fact, it's just sent for a handful of us that are testing this) thus right now you only get a verified primary email, and LDAP aliases if available, and they're in different fields
- Adding new emails will require going to your account on mozillians.org and adding them as 'external account', though these currently going to show as `verified:false` and will do so until mozillians.org supports verification (which we want!). Note that systems like phonebook do not verify these either right now.

# On identifying users
Identifying users is somewhat difficult because our login options do not provide the same degree of guarantee that their identity has been verified: passwordless does not support MFA, and Google logins cannot assert if they have used MFA or not - unless the Google account is backed by Mozilla LDAP. This leaves us with GitHub (which, because they're awesome, added that feature on our demand), LDAP-backed Google accounts, and LDAP accounts with MFA. This means we do not, and do not want to associate these with 'weaker' identities.

## In other words:

If you have `bob@example.net` logging in with passwordless/email and...`bob@example.net` also sometimes logs in with GitHub+MFA, we do not want to associate them. One is strongly verified, the other one is not, thus an attacker would just use the weaker method to get access to the account and make MFA and password verification **useless** and that's scary for us.

Our solution to help out there and ensure RPs get correct expectations is that we most likely won't let you login with weaker accounts that have the same primary emails as a 'stronger' account in the very near future.

I believe that last point will actually solve most of your problems, or at least would hope that this is a step in that direction. Ideally though, I think standups should prompt the user when it detects a new user (I suspect it does not to get a better conversion rate, so it's up to you).

## On lock/login screen behavior
Finally, I'm not 100% sure it that's going to help, but we're also looking at collecting data regarding the lock/login screen behavior where you click your username to login with it. If enough data is gathered with people who are annoyed by that behavior, we might turn it off (which means once logged in you're always on the same user until you purposefully log yourself out of SSO). This may either set better expectations, or make the problem worse ;-)

Discussion regarding this here: https://discourse.mozilla.org/t/the-last-time-you-logged-in-with-button/19468

**Comment by willkg** [comment]
Since we did anything here, the Mozilla SSO has undergone some changes including one which essentially makes using Standup with a non-LDAP account super duper really hard if you have an LDAP account.

The use case here covers people who have an LDAP account, but want to use a different account on Standups. Because of the Mozilla SSO changes, I think that use case is moot now.

Given that, I think it makes more sense not to do anything here and make Standups more complex.

Given that, I'm going to close this out.

**Comment by gdestuynder** [comment]
@willkg see https://github.com/mozilla-iam/auth0-custom-lock/issues/34 if you're interested in how we plan to evolve the way the login form works

**Comment by willkg** [comment]
@gdestuynder Standup is a side project that has no staff and no contributors. I can't keep up with changes to the lock and IAM thinking. Seems like there are interesting things happening--that's great!

However, I think the best option for Standup is a "You have to use LDAP if you have one" policy. There are definite disadvantages for users, but it is the easiest to support, doesn't require more code, and it seems like it's the least likely to require changes as IAM changes things.

If someone doesn't like it--that's ok. I *highly* encourage them to get involved and help with the work burden.

**Comment by gdestuynder** [comment]
No problem :) I just put this as an informational/FYI kind of thing
