### ISSUE TITLE
Cannot login m_kato account via github auth provider

### ISSUE THREAD

**Issue by makotokato** [mozilla/standup#437]
Although I use github auth provider, I cannot login via github account to standup.  Error message is the following.

> Sorry, you may not login using GitHub. Please instead always login with LDAP.

My standup account is m_kato, Also, github account is @makotokato.  Also if we cannot fix this, please change to LDAP account (m_kato@ga2.so-net.ne.jp or mkato @ moco)

**Comment by willkg** [comment]
I think that error message is coming from Mozilla SSO. Pretty sure they're changing things so that if you're using a Mozilla identity, you have to log in with LDAP.

You'll need to use your LDAP account to log into Standup.

Easiest thing to do is log in with your LDAP account and then let me know which accounts to merge.

**Comment by makotokato** [comment]
Thank you.

I used https://www.standu.ps/user/m_kato/ for non-Moco account (via github).  And I would like to keep this account (m_kato) via mkato@mozilla.com.

So could you remove https://www.standu.ps/user/mkato/ and change login account to mkato@mozilla.com for m_kato?

**Comment by willkg** [comment]
I'm soooo sorry I didn't do this earlier--it fell off my radar.

I merged the two accounts and updated the m_kato account with the mozilla.com identity.

You might have to log out and log back in again. After that, I think you should be all set! Let me know if you have any issues.
