### ISSUE TITLE
merge accounts

### ISSUE THREAD

**Issue by jdm** [mozilla/standup#448]
I was using my github account to login for the past few months, and recently I lost the ability to log in with it. Now I'm stuck with my ldap account which can't use the github or IRC name from my other account.

**Comment by jdm** [comment]
If the answer is just to merge the accounts, then josh@joshmatthews.net is the github one, and jmatthews@mozilla.com is the LDAP one.

**Comment by willkg** [comment]
If you're a moco employee, you have to use your moco account because of the changes they made to our auth0 sso. We added a note about that to the faq a while back.

You can only use github/passwordless methods if you're not a moco employee. Sorry about that!

I'll merge the accounts when I get a chance.

**Comment by willkg** [comment]
I merged the mozilla.com into the joshmatthews.net account. You should be all set. Let me know if you have any problems!
