### ISSUE TITLE
Identity issue

### ISSUE THREAD

**Issue by a2sheppy** [mozilla/standup#472]
Trying to log in using LDAP I'm getting the " If you think you already have an account with a profile, then log out and let us know. We can check the database and merge your accounts. " message. My email address is eshepherd@mozilla.com and my Standu.ps handle is "sheppy".

**Comment by willkg** [comment]
@a2sheppy I only see one account with "shep" in it, so I think you're ok.

We've had problems with people logging in with the wrong account in the past and then posting with the wrong account, so that message was added as a helper that everyone sees on logging in.

Are there other indicators that you have multiple accounts?

**Comment by willkg** [comment]
I'm going to close this out. It's probably fine now.
